### ISSUE TITLE
UI issue in footer (Safari and Chromium)

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#108]
Voila ce que j'ai avec Safari en plein écran (retina) :
<img width="1273" alt="Capture d’écran 2019-12-27 à 09 10 03" src="https://user-images.githubusercontent.com/7377177/71508673-ea500f00-2888-11ea-9301-19d88ccc7edd.png">

PS : pas de soucis sur Firefox avec la même config.

**Comment by JulioJu** [comment]
Same problem with Chromium. I've found the solution :-). I make the PR .

**Comment by JulioJu** [comment]
The problem is no Retina.
