### ISSUE TITLE
UI issue in header (Safari)

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#109]
Voila ce que j'ai sur Safari, en plein écran (retina) :
<img width="498" alt="Capture d’écran 2019-12-27 à 09 15 22" src="https://user-images.githubusercontent.com/7377177/71508852-7c581780-2889-11ea-9170-472ad66ac7a5.png">

PS : pas de problème avec Firefox sur la même config

**Comment by JulioJu** [comment]
With which version of Safari ? Since 2017, Safari support grid-css .

**Comment by jibidus** [comment]
Last version of course 😉 : `13.0.4`.
