### ISSUE TITLE
[UI] Flying Header does not 100% width

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#117]
Testé sur Safari et Firefox sur Mac, plein écran (retina) :

<img width="1277" alt="Capture d’écran 2019-12-30 à 08 48 27" src="https://user-images.githubusercontent.com/7377177/71572836-46ad6b80-2ae1-11ea-8a58-737cfc397984.png">

**Comment by JulioJu** [comment]
Oui oui c'est ce que j'avais dit sur Slack ;-) . Je m'en suis aperçu après. Comme je disais, pourtant ça se voit comme le nez au milieu de la figure. Pas encore corrigé :-)
