### ISSUE TITLE
[UI] Issues in article styling

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#118]
Il y a plusieurs soucis sur le styling des articles de blog, comme par exemple sur [cet article](https://blog.sogilis.fr/posts/2019-01-11-object-mother-builder-java/) :

- Il y a plus de marge en-dessous qu'en-dessus des titres.
- Il y a beaucoup moins de marge entre les lignes

## Avant
<img width="718" alt="Capture d’écran 2019-12-30 à 09 14 07" src="https://user-images.githubusercontent.com/7377177/71573555-c557d800-2ae4-11ea-8ee8-c897a4cbc80e.png">

## Après
<img width="718" alt="Capture d’écran 2019-12-30 à 09 14 00" src="https://user-images.githubusercontent.com/7377177/71573552-c38e1480-2ae4-11ea-91ab-aa2f8a0d1979.png">

**Comment by JulioJu** [comment]
Cool merci. Ça c'est probablement un effet de bord des modifications que j'ai fait sur les scss. Je vais corriger :-).

**Comment by jibidus** [comment]
ℹ️ J'ai modifié un peu de ticket, j'ai repéré un autre problème du même ordre.

**Comment by JulioJu** [comment]
Ok. Je m'attaque à la page article :-)
