### ISSUE TITLE
[UI] Snippet styling has changed

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#119]
Testé sur Safari et Firefox, par exemple sur [cet article](https://blog.sogilis.fr/posts/2019-01-11-object-mother-builder-java/).

## Before
<img width="733" alt="Capture d’écran 2019-12-30 à 09 11 03" src="https://user-images.githubusercontent.com/7377177/71573471-5a0e0600-2ae4-11ea-98e5-6569e9bc11e7.png">

## After
<img width="730" alt="Capture d’écran 2019-12-30 à 09 08 15" src="https://user-images.githubusercontent.com/7377177/71573417-0dc2c600-2ae4-11ea-8ccd-87a6c4c293e2.png">

**Comment by JulioJu** [comment]
Merci pour la remarque. Pareil que pour #118 . Je n'avais pas travaillé sur cette page hier, j'ai donc modifié un truc qui a un effet sur cette page sans que je m'en aperçoive .

**Comment by JulioJu** [comment]
Not all is fixed. See #140 what is not fixed.
