### ISSUE TITLE
[UI] Menu styling has changed

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#121]
Testé sur Firefox et Safari sur mac (en plein écran), que ce soit le menu de base (sans avoir scrollé) ou le menu flotant (une fois qu'on scroll down), les 2 ont changé.

## Avant
<img width="1279" alt="Capture d’écran 2019-12-30 à 09 37 25" src="https://user-images.githubusercontent.com/7377177/71574196-08677a80-2ae8-11ea-8f91-f46a0bdb5d29.png">

## Après
<img width="1279" alt="Capture d’écran 2019-12-30 à 09 37 21" src="https://user-images.githubusercontent.com/7377177/71574191-02719980-2ae8-11ea-9fe0-8eb644f3fd70.png">

**Comment by JulioJu** [comment]
@jibidus je me suis basé sur la taille du site https://sogilis.fr et https://sogilis.com . Donc en effet je l'ai grossis par rapport à l'ancienne charte graphique du blog, mais je l'ai rapproché de la charte graphique des sites web. Qu'en penses-tu ?

**Comment by jibidus** [comment]
Si ça match avec le site web, ça me semble bien.
Par contre, chez moi, ça ne match pas (testé sur Safari & Firefox).
