### ISSUE TITLE
[UI] Article card styling is broken on Chromium and Safari

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#122]
Les images des article prennent toute la hauteur de la carte.
Testé sur Safari sur mac (plein écran).
Voila ce que ça donne :
<img width="1279" alt="Capture d’écran 2019-12-30 à 09 45 22" src="https://user-images.githubusercontent.com/7377177/71574583-a60f7980-2ae9-11ea-93d2-2b4df75b031e.png">

**Comment by JulioJu** [comment]
Fixed by #123
