### ISSUE TITLE
[UI] Menu for mobile device

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#130]
Sur mobile, avec une largeur d'écran de 600 (DRP 2), le style du burger menu est "cassé". La barre séparatrice bleu se retrouve dans le texte et l'interligne semble un peu trop faible.

Testé sur Safari et Firefox en vue adaptative.

## Voila ce que ça donne
<img width="401" alt="Capture d’écran 2019-12-31 à 09 32 25" src="https://user-images.githubusercontent.com/7377177/71615261-b2123e80-2bb0-11ea-803f-036112eba0dd.png">

## Voila ce qu'on a sur sogilis.fr
<img width="291" alt="Capture d’écran 2019-12-31 à 09 34 43" src="https://user-images.githubusercontent.com/7377177/71615283-cce4b300-2bb0-11ea-9765-7ce247dbbf2a.png">

**Comment by JulioJu** [comment]
Not fixed. See #139 .
