### ISSUE TITLE
Replace _compass_reset.scss and Bootstrap by Reboot

### ISSUE THREAD

**Issue by JulioJu** [sogilis/Blog#137]
See https://getbootstrap.com/docs/4.0/content/reboot/

What do you think about that @jibidus ? 

Warning, as I've said, ti's role is different of normalize.scss (see https://github.com/sogilis/Blog/issues/95 )

Relative issues : https://github.com/sogilis/Blog/issues/80 and https://github.com/sogilis/Blog/issues/78

**Comment by jibidus** [comment]
Je n'ai pas bien pigé ce que faisait Reboot & co, du coup difficile de donner un avis.

**Comment by JulioJu** [comment]
Done thanks #155 .
