### ISSUE TITLE
[UI] [Mobile] Burger menu is broken

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#139]
Le trait horizontal du burger menu n'est pas aligné avec le texte
<img width="412" alt="Capture d’écran 2020-01-03 à 07 29 58" src="https://user-images.githubusercontent.com/7377177/71710124-090b5400-2dfb-11ea-839e-79fd2ae8d571.png">

Testé sur Safari.

**Comment by JulioJu** [comment]
Already reported on #130 . I thought it was fixed, but sorry, no.

**Comment by JulioJu** [comment]
I don't see any problem. 

Actually, the position of the bar is fixed. When the height of the screen is small, or with you zoom too much, we have the same problem on sogilis.fr or blog.sogilis.fr .

Therefore it seems not to be a regression, but simply a configuration different of your browser.

Anyway, I will going to try to change this behavior.

**Comment by jibidus** [comment]
Je n'ai pas le même chose entre blog.sogilis.fr et sogilis.fr :

# sogilis.fr
<img width="556" alt="image" src="https://user-images.githubusercontent.com/7377177/73133074-10053b00-4024-11ea-8050-d1ec682a83f4.png">

# blog.sogilis.fr
![image](https://user-images.githubusercontent.com/7377177/73133089-43e06080-4024-11ea-9741-d856ef578246.png)

Screenshots pris avec Safari en vue adaptative (Safari - iOS 12.1.3 - iPhone), scale x2.

**Comment by JulioJu** [comment]
De tout façon, ce sera réparé avec le refacto que je réalise.

**Comment by JulioJu** [comment]
Done thanks #155
