### ISSUE TITLE
[UI] Code snippet styling altered

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#140]
Le style des extraits de code semble altéré.

## Voila ce qu'on a :
<img width="462" alt="Capture d’écran 2020-01-03 à 07 29 33" src="https://user-images.githubusercontent.com/7377177/71710199-5982b180-2dfb-11ea-8c1d-bd4960db3c9e.png">

## Ce qu'on avait avant :
<img width="462" alt="Capture d’écran 2020-01-03 à 07 29 44" src="https://user-images.githubusercontent.com/7377177/71710206-5d163880-2dfb-11ea-8deb-2bb16e4b6717.png">

Testé sur Safari, sur l'article https://blog.sogilis.fr/posts/2019-01-11-object-mother-builder-java/

**Comment by JulioJu** [comment]
See also #119 . Some parts of the issue #119 was fixed, but not all!

**Comment by JulioJu** [comment]
@jibidus corrigé grâce à #155
