### ISSUE TITLE
Configure Google Analytics

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#174]
Voici quelques infos en vrac :
- Il existe un compte UX Shadow (cf Basecamp)
- `Google marking Plateform` semble un un "pack" niveau entreprise pour gérer tous les outils marketing, notamment `Google Analytics`. D'ailleurs, pour partager un compte `Google Analytics` a un groupe, il faut passer par `Google marking Plateform`
- Il existe plusieurs tuto (comme [celui-ci](https://www.soberkoder.com/google-analytics-hugo/)) qui explique comment activer `Google Analytics` dans Hugo.
- Si coût faible, voir pour activer `Google Analytics` aussi sur les sites internet (`fr` et `com`).

⚠️ RGPD : complique probablement la chose en nécessitant un accord du visiteur (voici un plugin qui permet cela https://tarteaucitron.io/fr/)

Echéance : novembre

**Comment by JulioJu** [comment]
@jibidus Nicolas l'a déjà configuré pour sogilis.fr. Je ne sais pas si on peut réutiliser ce qu'il a fait.

**Comment by bdumas1** [comment]
> @jibidus Nicolas l'a déjà configuré récemment pour sogilis.fr. Je ne sais pas si on peut réutiliser ce qu'il a fait.

Non car il mis le code Google Analytics [en dure dans le code ](https://github.com/sogilis/sogilis.fr/blob/master/index.html#L59), et ce n'est pas RGPD friendly. Tout le monde devrait pouvoir avoir la possibilité de choisir si oui ou non il souhaite être tracé par cet outil.

**Comment by vlamy** [comment]
On pensait plutôt essayer un truc du genre https://fr.matomo.org/

**Comment by JulioJu** [comment]
@bdumas1 j'avais pas pensé à cette problématique. Perso moi je désactive Google Analytics au nivau du navigateur donc j'ai pas ce problème ;-) .
