### ISSUE TITLE
[Doc] Describe supported Markdown format precisely

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#185]
Objectif : permettre de savoir précisément ce qu'il est possible de faire et ce qui ne l'est pas lors de la rédaction d'articles en Markdown.

**Comment by JulioJu** [comment]
Si je peux me permettre. Je pense que le préférable est de renvoyer vers une documentation officielle. Ce sera probablement toujours mieux mis à jour et mis à jour et mieux maintenu que ce que l'on ferait nous.

**Comment by jibidus** [comment]
Je suis d'accord, mais je n'en n'ai pas trouvé. Tu as ça ?

**Comment by JulioJu** [comment]
https://gohugo.io/content-management/formats/#learn-markdown  peut-être ?

**Comment by jibidus** [comment]
Cf https://github.com/sogilis/Blog/pull/181#discussion_r501539991

**Comment by JulioJu** [comment]
Sur https://github.com/gohugoio/hugo je vois beaucoup de références à `commonmark`. 

Tout ne semble pas implémenter, mais ça me paraît être uen bonne base.

Je crains que ce ne soit pas pertinant qu'on documente nous de notre côté ce que fait Hugo ou ce qu'il ne fait pas. Surtout que ça risque d'être sujet à régression, évolution, amélioration.

Dans ta PR #181 peut-être peux-tu ajouter que tout CommonMark n'est pas implémanté dans Hugo. Et inciter les personnes qui voient un bug dans Hugo à l'ajouter dans une liste à puce de notre côté et faire un lien vers un ticket ouvert chez Hugo, et donc ouvrir le ticket chez Hugo s'il n'existe pas encore et si ce n'est pas répertorié.

Qu'en penses-tu ?

**Comment by jibidus** [comment]
Plusieurs choses :

1. Je pense qu'il nous faut un document unique qui explique tout ce qu'il est possible de faire en Markdown. Sinon, les futures auteurs vont perdre du temps a essayer de choses, voir se décourager, voir utiliser des trucs tordus (ex: les footnotes dans les derniers articles comme [celui-ci](https://github.com/sogilis/Blog/blob/master/site/content/posts/2020-09-09-bdd-qualite-eficience.md)). Oui, il serait préférable que cette page soit gérée par l'équipe Hugo (et idéalement que ça concerne la version précise de Hugo que l'on utilise), mais pour l'instant je n'ai rien vu de tel (je ne vois sur sur `commonmark` sur https://github.com/gohugoio/hugo). Bref, je ne vois pas solution idéale, il faut accepter le compromis et la page que j'ai proposé me semble un bon quick win.

2. Où as-tu vu que `CommonMark` n'était que partiellement implémenté ?

3. L'objectif d'un document décrivant le format précisément n'est pas décrire une thèse rentrant dans tous les détails (sauf si tu vois de la valeur a ce document, moi non), mais d'aider pour les futures auteurs. Le document doit donc fournir toutes les informations utiles et uniquement les informations utiles. Expliquer qu'il y a peut-être des bug, je ne pense pas que ce soit utile (c'est inhérent a tout logiciel, surtout dans le web). Par contre, il pourrait avoir du sens de ne pas parle de CommonMark ou Github Flavor et donner uniquement le lien https://www.markdownguide.org/tools/hugo/ (vu qu'on a vérifier que tout ce qui y est indiqué fonctionne).

**Comment by JulioJu** [comment]
1. ok merci pour ton explication ! Oui super !

2. https://github.com/gohugoio/hugo/issues?q=is%3Aissue+is%3Aopen+commonmark :-)

3. Ah oui trop cool ce lien https://www.markdownguide.org/tools/hugo/  !

**Comment by jibidus** [comment]
Parmi les 9 issues taggées `commonmark`, ce ne sont pas "juste" des bugs (et non des trucs non implémentés) ?
Parce que si ce sont des bugs, alors n'est-ce pas normal ? Je veux dire qu'alors, quelque soit la lib utilisée, on aura des bugs, et du coup, pourquoi le mentionné dans la doc ? Après, s'il y en a plus que ce qu'on peut s'attendre, oui il vaut mieux le dire (mais 9 me parait peu pour un projet de ce type).

**Comment by JulioJu** [comment]
Oui 9 c'est peu !

Je n'ai pas regardé le détail…
