### ISSUE TITLE
Improve readability of code block with another font

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#202]
Many with [JetBrains Mono](https://www.jetbrains.com/lp/mono/)?

**Comment by JulioJu** [comment]
Peut-être à valider avec Nicolas  (simplement en lui posant la question) .

**Comment by jibidus** [comment]
This could help (gist with css to use Jetbrains-Mono): https://gist.github.com/Albert221/753d7f8955eeb6f5e50486fce048e39f

**Comment by jibidus** [comment]
# Today
<img width="540" alt="Capture d’écran 2020-11-04 à 11 26 55" src="https://user-images.githubusercontent.com/7377177/98100218-d3a71b00-1e90-11eb-88c5-e5c6a2c41dd6.png">

# With Jetbrains Mono
<img width="540" alt="Capture d’écran 2020-11-04 à 11 26 33" src="https://user-images.githubusercontent.com/7377177/98100226-d73aa200-1e90-11eb-8ea2-1359ccdcb88c.png">
