### ISSUE TITLE
Blog articles contains errors

### ISSUE THREAD

**Issue by Nas84** [sogilis/Blog#5]
**Describe the bug**
Actually the articles contains several types of issue, for example, the link to images are broken or used http:// link instead of https://. it contains also severa lwierd characters. 

**To Reproduce**
1. Go to 'the deployed linked 
2. Click on 'any blog articles
3. See error

**Expected behavior**
A clear articles should be available without any formating, link, images errors.

**Screenshots**

**Desktop (please complete the following information):**

 - Browser : chrome, firefow
 - Version: hugo 0.58.6

**Comment by Nas84** [comment]
@thimaisogilis as discussed i am taking the most recent and you take the oldest articles.  I am going to migrate 4-5 articles per day.

**Comment by Nas84** [comment]
Progres mades with #15

**Comment by jibidus** [comment]
Fixed in :
- #32 for images with http
- #30 broken images
