### ISSUE TITLE
[UI][Footer] Superposition de composants

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#51]
Lors que l'écran est réduit (1/2 écran en gros).
Voila ce que ça donne : 
<img width="378" alt="Capture d’écran 2019-11-28 à 12 41 06" src="https://user-images.githubusercontent.com/7377177/69803545-c099be80-11dc-11ea-9c68-6a5a74c57cef.png">

Browser : Safari
OS : macOS

**Comment by JulioJu** [comment]
Ce bug apparaît aussi sous Firefox 71 et Chromium 78.

**Comment by JulioJu** [comment]
@Jibidus pour le problème du footer, pour résoudre le probleme de la superposition des composants sur certaines dimension d'écran, j'utilise les css grids. 

Il semblerait que l'on ne puisse pas résoudre cela grâce à Bootstrap, car Bootstrap divise une ligne en 12 colonnes de tailles identiques. Il semblerait qu'on puisse bidouiller en utilisant des style inline (voir exemple https://stackoverflow.com/questions/30026855/can-i-give-the-col-md-1-5-in-bootstrap/30027585 ) mais je ne sais pas si c'est le mieux. 

Les css-grid, c'est vraiment cool. C'est solide. Et ça évitera de mettre des margins et des paddings dans tous les sens. En plus, avec Firefox (pas avec Chrome), ça se débug vraiment super facilement. En ce sens, c'est plus simple et clair que Flexbox je trouve ;-). 

Mais bon, je ne sais pas si c'est ce que tu préférerais. 

Je pourrai te montrer cela de visu, peut-être !

**Comment by JulioJu** [comment]
Je suis en train de préparer la PR, je finirai plus tard…

**Comment by jibidus** [comment]
Aucune idée, je n'ai pas du tout regardé.
C'est Nico qui a produit le CSS. Il y a certainement des choses à améliorer, c'est difficile à maintenir tel quel.

**Comment by JulioJu** [comment]
@jibidus merci pour ta réponse.
Je regarderai plus en détail demain :-)
