### ISSUE TITLE
[UI] Problème avec la hauteur des blocs (cf Nico)

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#53]

**Comment by JulioJu** [comment]
Bonjour,

Quel est le problème avec la taille des blocs ;-) ?

Merci par avance pour la précision :-)

**Comment by jibidus** [comment]
J'imagine que @nicolaserre aurait plutôt vu des hauteurs fixes pour tous les bloques.
@nicolaserre, tu confirmes ?

**Comment by nicolaserre** [comment]
Exactement.

**Comment by JulioJu** [comment]
@jibidus j'ai commencé à fixer le problème. C'est simple à résoudre. Je m'en occupe dès que je peux.

**Comment by JulioJu** [comment]
Done with #105
