### ISSUE TITLE
Remove `_compass_reset.scss`

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#78]

**Comment by JulioJu** [comment]
Pourquoi souhaites-tu supprimer ce fichier ?

**Comment by jibidus** [comment]
Parce qu'il ne doit probablement servir à rien (on ne sait pas pourquoi il est là).
Il a l'air de setter toutes les propriétés à des valeurs par défaut.
S'il y a des choses qui servent, c'est qu'il manque des choses dans notre css à priori.

**Comment by JulioJu** [comment]
Si, il sert ;-) ! En tout cas, y'a des éléments du footer qui s'en servent ;-) . De tout façon, le scss est peut-être pas optimal. Il n'est pas factorisé, et ça pose problème en termes de lisibilité ;-) 

Il faudrait il me semble factoriser, ce serait la proirité sur supprimer ce fichier ;-)

**Comment by JulioJu** [comment]
See #133 

Actually, there all this file is commented, except two declarations.

Will be deleted at the end of #100 .
