### ISSUE TITLE
Delete third party assets

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#80]

**Comment by JulioJu** [comment]
I would like delete all third parties assets. 

It seems that Bootstrap is used only for its grid system. During my work of factorization, I remove this, and replace it by Flexbox. Under the hood, Bootsrap uses Flexbox. Therefore no need of Boostrap, just use bar Flexbox

JQuery is used only for one or two getElement, could be deleted too very easy.

**Comment by JulioJu** [comment]
Lot of third parties assets has been commented (but not deleted) in https://github.com/sogilis/Blog/commit/e8ba465c54a94da1868e5c7c2b0bb6cc8feacbcf 

They should be deleted .if it's confirmed that there are no impacts. 

Bootstrap ant JQuery can't be deleted actually. But soon I hope ;-)

**Comment by JulioJu** [comment]
Done thanks #155 .
