### ISSUE TITLE
[UI][Header] 992/1064 px inclus barre de navigation sur 2 lignes

### ISSUE THREAD

**Issue by JulioJu** [sogilis/Blog#84]
**Describe the bug**

Bettween 992 pixels and 1064 pixel include, the bare of navigation is on two lines.

**To Reproduce**
Test with Responsive Design Mode on Firefox or Chromium

**Expected behavior**
It's better if it's on one line ;-). 

**Screenshots**
![BarreNav2Lignes](https://user-images.githubusercontent.com/11527844/69912159-a43c9280-1425-11ea-95ef-e8d015deb68c.png)

**Desktop (please complete the following information):**

 - Browser: Firefox 71 or Chromium 78

 - Platform:  Arch Linux

**Comment by jibidus** [comment]
We got the same issue in `sogilis.com` and `sogilis.fr`!

**Comment by JulioJu** [comment]
Yes I've see ! As for the footer ;-) !  See https://github.com/sogilis/Blog/issues/51 . 

I would like to try to resolve this tomorrow.

**Comment by jibidus** [comment]
Would be great!
