### ISSUE TITLE
Certains liens s'affichent mal

### ISSUE THREAD

**Issue by jibidus** [sogilis/Blog#87]
Exemple sur https://blog.sogilis.fr/posts/2016-09-06-srp-single-responsibility-principle-code/ :
<img width="431" alt="Capture d’écran 2019-12-02 à 14 59 03" src="https://user-images.githubusercontent.com/7377177/69965370-666a6780-1514-11ea-8dfe-6be4eb72d09d.png">

Alors que [en local](http://localhost:3000/posts/2016-09-06-srp-single-responsibility-principle-code/), pas de problème :
<img width="77" alt="Capture d’écran 2019-12-02 à 15 00 46" src="https://user-images.githubusercontent.com/7377177/69965425-8ac64400-1514-11ea-84c8-f85a7eb2ebda.png">

**Update:**
Le problème est bien présent en local, sauf lorsqu'on lance le blog directement (sans passer par `Docker`) avec `yarn start`.

**Comment by JulioJu** [comment]
De mon côté, sous la branche master, j'ai également le problème en local. Bizarre qu'on n'ait pas le même problème.
