### ISSUE TITLE
Add normalize.scss

### ISSUE THREAD

**Issue by JulioJu** [sogilis/Blog#95]
To  consistent base style across all browsers, maybe we should use normalize.scss .

See for instance https://sam.hooke.me/note/2018/02/normalize-scss-with-hugo/ .

What do you think about that @jibidus  ?

**Comment by jibidus** [comment]
Didn't know such tools. Could be useful.
Do you notice a significant difference between two browsers in current version of the blog?

I think that `_compass_reset.scss` has the same purpose than `normalize.scss`.

**Comment by JulioJu** [comment]
Don't check. But I didn't check on Safari, IE, Opera, Edge, etc. 

The goal of ` _compass_reset_scss` is different of `normalize.scss` .

>  The goal of a reset stylesheet is to reduce browser inconsistencies in things like default line heights, margins and font sizes of headings, and so on. 
 > (` _compass_reset_scss`)

For instance, Firefox could say that by default margins are defined at 6 px, and Edge at 5 px. As the default value of the margin is not defined in the specification, each browser could define its.

As we use Bootstrap, it's not a good idea to use `_compass_reset.scss` . But we must check that remove this file don't 

The goal of `normalize` is different : 

> Normalize.css corrects common bugs
> It fixes common desktop and mobile browser bugs that are out of scope for resets. This includes display settings for HTML5 elements, correcting font-size for preformatted text, SVG overflow in IE9, and many form-related bugs across browsers and operating systems.

Especially, normalize add prefixed css rules, prefixed with vendor rules (like `ms`, `moz`, `webkit`). Some navigators don't implement css standard rules, but implements the rule with its own prefix (`moz`, `ms`, etc.). 

I hope I'm clear ;-)

Normalize add rules. Reset don't add rules. 

See more details.
More details about this http://nicolasgallagher.com/about-normalize-css/

**Comment by JulioJu** [comment]
Je ne sais pas si j'ai été clair quand je t'ai dit en quoi normalize.scss était intéressant. 

Genre, tu as l'attribut css transition: normalisé par la w3c. Certains vieux navigateurs implémentent cette fonctionnalité avec un préfixe. Genre les vieux Safari ou Chromium, avec le préfixe `-webkit-`, les vieux Firefox avec `-mz-`, Opera avec `-o-`, ie / Edge avec `-ms-`.  Comme @nicolaserre  tu sais que que les vieux navigateurs ne comprennent pas l'attribut `transition:` mais soit `-mz-transition`, `-o-transition` , `-webkit-transition` . Tu as donc ajouté ces attributs directement dans le code source (les fichiers scss). Résultat on se retrouve avec des déclarations du genre `-webkit-transition: all 0.3s; -moz-transition: all 0.3s; -o-transition: all 0.3s; transition: all 0.3s;` alors qu'on pourrait écrire simplement `transition: all 0.3s;` Normalize.scss permet d'ajouter à la transpilation les attributs propriétaires avec préfixe compris par les vieux navigateurs. Grâce à lui je vais virer tous les attributs propriétaire du code source, ce qui va permettre d'avoir un fichier plus courts et donc plus clairs ;-) .

**Comment by jibidus** [comment]
Ah oui, c'est top ça !

**Comment by JulioJu** [comment]
Je confonds normalize.scss et auto-prefixer. Désol.
